### ISSUE TITLE
RuntimeError: No CUDA implementation of 'geev'.

### ISSUE THREAD

**Issue by laiviet** [TomHeaven/pytorch-osx-build#18] opened 2021-03-23 09:42 UTC
I place the magma folder in /usr/local/lib as /usr/local/lib/magma/lib/libmagma.dylib. Is it right?

Traceback (most recent call last):
  File "dc.py", line 165, in <module>
    main(args)
  File "dc.py", line 148, in main
    perf, loss = model.fit_and_evaluate(sx_emb, sy, qx_emb, qy)
  File "/Users/vietl/projects/ed-fsl/fewshot/metaopnethead.py", line 628, in fit_and_evaluate
    qp_sol = QPFunction(verbose=False)(G, e, C, h, dummy.detach(), dummy.detach())
  File "/Users/vietl/.miniconda3/envs/py37/lib/python3.7/site-packages/qpth/qp.py", line 83, in forward
    e, _ = torch.eig(Q[i])
RuntimeError: No CUDA implementation of 'geev'. Install MAGMA and rebuild cutorch (http://icl.cs.utk.edu/magma/) at /Volumes/Data/library/pytorch/aten/src/THC/generic/THCTensorMathMagma.cu:193

**Comment by TomHeaven** [comment] 2021-03-24 13:18
Thanks for the remind! 

`torch.eig()` with CUDA seems to be broken in Pytorch 1.8.  I'll try to find the cause.

For now, you can use [Release v1.7](https://github.com/TomHeaven/pytorch-osx-build/releases/tag/v1.7.0_cu101) instead, which seems to be stable and fully functional.

**Comment by llv22** [comment] 2021-08-13 08:17
@TomHeaven has the issue mentioned above been fixed in your pytorch 1.9 cuda version? I'm curious about this

**Comment by TomHeaven** [comment] 2021-08-29 16:55
No. The issue is introduced in v1.8 and still not fixed in v1.9.

**Comment by llv22** [comment] 2021-10-20 03:51
@TomHeaven one question about the magma used in torch macOS compilation
I actually used source code on https://bitbucket.org/icl/magma/src/master/ with 2.5.4 version and compiled it on my computer with cuda 10.1 and xcode version as you mentioned in torch for macOS.
Have you checked with the root cause of torch.eig() issue? if it is, could you share with me?
My gut feeling is that in case we recompiled magma on our macOS, perhaps such missing implementation issue can be resolved. Or there may be a pit behind...
Anyway, will check it and update you later.

**Comment by llv22** [comment] 2021-10-24 09:45
@TomHeaven @laiviet I compile magma local with cuda 10.1, then use pytorch 1.8 with your patch. the good news is torch.eig() seems working. put my magma for 2.6.1 in https://github.com/llv22/magma-macOS/tree/v2.6.1-built for your reference.

**Closed as completed** 2021-10-24 10:54 UTC

**Comment by llv22** [comment] 2021-10-26 03:02
@laiviet if you want to compile 1.9.1 + magma part, you can use https://github.com/llv22/pytorch-1.9.1-macOS-cuda and https://github.com/llv22/magma-macOS/tree/v2.6.1-built. In the former part, I enabled torch.distributed via gloo and commented out unnecessary python codes that were coupled with tensorpiple. Basically now torch 1.9.1 on cuda 10.1 + cudnn7.5.6 could work now. For migration 1.10.0, still need a longer time as it requires cuda 10.2, which is different from what I and tom used to compile tensorflow and pytorch.

**Comment by TomHeaven** [comment] 2022-03-16 08:06
@llv22 
+ It's great to hear that `torch.eig()` issue seems to be solved by upgrading magma.
+ It's exciting that you successfully make `nccl-osx` work. It will unlock NCCL related distributed functions for pytorch & tensorflow.
+ You can use the new source patches from my repo to bypass the cuda version check in pytorch 1.10.0.

**Comment by llv22** [comment] 2022-03-16 08:32
@TomHeaven yeah, I also crack 1.10.0. But I found tensorpipe heavily relies on glibc hosted in ubuntu linux. Currently I disable tensorpiple on mac, but the later version of pytorch requires tensorpipe sadly...
Perhaps one cure-all is to hack glibc a little bit on mac, so that we won't suffer from missing tensorpipe anymore. Regarding if it is possible, let me bit the code a little bit......hopefully.....

**Comment by TomHeaven** [comment] 2022-03-24 07:04
The issue is fixed in the new release: https://github.com/TomHeaven/pytorch-osx-build/releases/tag/v1.10.0_cu101_distributed. @laiviet
